### ISSUE TITLE
Cannot find Run-plink.sh

### ISSUE THREAD

**Issue by Celestic1** [eauforest/imputePrepSanger#6]
Hello, I am running the pipeline and encountering this error:

chmod: cannot access ‘Run-plink.sh’: No such file or directory
./imputePrep_script.sh: line 69: ./Run-plink.sh: No such file or directory

I don't seem to find this script anywhere. Do I have to create my own?

**Comment by michellekee** [comment]
I’m having this problem too. May I know how was yours resolved?
